- defaults:
    link:
      create: true
      relink: true
    shell:
      quiet: true

- clean: ['~']

- link:
    ~/.config/nvim: 
      create: true
      path: nvim/**
      glob: true
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig: 
    ~/.local/share/fonts:
      create: true
      path: fonts/*
      glob: true
    ~/.shell:
    ~/.tmux.conf:
    ~/.tmuxifier: tmux/plugins/tmuxifier
    ~/.vimrc:
    ~/.zshrc:

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >-
    git cleanall -f
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
