- defaults:
    link:
      create: true
      relink: true
    shell:
      quiet: true

- clean: ['~', '~/.oh-my-zsh/custom/plugins/']

- shell:
  - [sh pre-install.sh, Running pre installation script]

- link:
    ~/.config/alacritty/alacritty.toml:
      path: alacritty
    ~/.config/nvim: 
      path: nvim/**
      glob: true
      force: true
    ~/.config/lazygit/config.yml:
      path: lazygit
      force: true
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
      force: true
    ~/.dotfiles: ''
    ~/.gitconfig: 
    ~/.gitmessage:
    ~/.oh-my-zsh/custom:
      path: oh-my-zsh/custom
      force: true
    ~/.shell:
    ~/.tmux:
    ~/.tmux.conf:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
      force: true

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >-
    git cleanall -f
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
