- defaults:
    link:
      create: true
      relink: true
    shell:
      quiet: true

- clean: ['~']

- link:
    ~/.config/nvim: 
      path: nvim/**
      glob: true
      force: true
    ~/.config/lazygit/config.yml:
      path: lazygit
      force: true
    ~/.config/mise/config.toml:
      path: mise
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig: 
    ~/.oh-my-zsh/custom:
      path: oh-my-zsh/custom
    ~/.shell:
    ~/.tmux:
    ~/.tmux.conf:
    ~/.vimrc:
    ~/.zshrc:

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >-
    git cleanall -f
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
